### PR TITLE
Changed tagName attribute

### PR DESCRIPTION
**Pull request by damiengo**
I had to change `node.tagName` to `node._tag_name` to make the app working.
I don't know why it do not work anymore with `tagName`, @MBach I let you see if this PR is useful or not.

### CODE REVIEW

**Comment by damiengo** [comment]
I think this PR is useful finally, on [fdroid data](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7452#note_419523534) it builds but nothing is displayed, like on my phone before correcting.

**Comment by MBach** [comment]
I'll have a look if this changes something!
By the way, it works fine when I build the App with Android Studio

**Comment by damiengo** [comment]
Ok, I don't know why it did not work for me. 

I build the app with `npm run start` and `npm run android`, and nothing was displayed.
If you download the apk given on [this link](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7452#note_419523534) when it is built on fdroid, you will have the same result, nothing is displayed...

**Review by MBach — APPROVED** [review]

**Comment by MBach** [comment]
OK, tested and it's working fine with _tag_name attribute

**Pull request merged**
